// Generated by CoffeeScript 1.6.2
require(['app', 'jquery', 'bootstrap'], function(app, $) {
  'use strict';  console.log('ajax');
  return $('.btn-song').on('click', function() {
    window.global = {};
    window.req = $.ajax({
      url: './scripts/teen.json'
    });
    return window.req.done(function(d) {
      console.log(d);
      return $(d.objects).each(function() {
        console.log(this.body_chords_html);
        return $('.song-chords').html(this.body_chords_html);
      });
    });
  });
});
